import React from "react";
import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "../icons/icons.css";
import "./globals.scss";
import "./globalComponetnts.scss";
import "../styles/index.scss";

export const metadata: Metadata = {
  title: "ZKTeco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>{children}</body>
    </html>
  );
}
